site_name: ACMBPDC
theme: readthedocs
nav:
  - Home: 'index.md'
  - Sessions:
    - '1: Command Line Interface': './01-command-line-interface/README.md'
    - '2: Overview of Programming Languages': './02-overview-of-programming-languages/README.md'
    - '3: Data Structures' : './03-data-structures/README.md'
    - '4: Algorithms': './04-algorithms/README.md'
    - '5: Python - 1': './05-python-1/README.md'
    - '6: Python - 2': './06-python-2/README.md'
  # - '6: Python - 2': './06-python-2/ACM_BPDC_Python_2.ipynb'
    - '7: Git & GitHub - 1': './07-git-and-github-1/README.md'
  
# plugins:
#   - mkdocs-jupyter:
#       execute: True
#       execute_ignore: "./05-python-1/*.ipynb" 